clang-tidy stuff
gerbera/gerbera pull request #1237
Opened 2021-02-18 03:34 UTC by neheb

last commit was done manually. I pay have messed something up.

2021-02-18 06:17 UTC, KarlStraussberger requested changes
Some of the removed refs are breaking.

2021-02-18 06:17 UTC, KarlStraussberger commented on src/config/config_setup.h
> +    bool createArrayFromNode(const pugi::xml_node& element, std::vector<std::string> result) const;
The result parameter must be ref otherwise the added content ist not returned

2021-02-18 06:17 UTC, KarlStraussberger commented on src/config/config_setup.cc
> +bool ConfigPathSetup::checkPathValue(std::string& optValue, std::string pathValue) const
The `pathValue` is set as part of the operation

2021-02-18 06:17 UTC, KarlStraussberger commented on src/database/database.h
> +        std::vector<int> updateID, const std::map<std::string, std::string>& lastMetadata)
The vector is part of the result. Must be ref.

2021-02-18 06:17 UTC, KarlStraussberger commented on src/database/sql_database.cc
> +    std::vector<std::shared_ptr<AddUpdateTable>> operations)
The vector is part if the result

2021-02-20 08:02 UTC, KarlStraussberger commented
It's still breaking. Most of the refs in `config_setup` are return values.

2021-02-23 13:27 UTC, whyman commented
Did the changes that @KarlStraussberger ask for make it in? Doesnt look like more commits have been added?

2021-02-23 22:09 UTC, neheb commented
Updated.

2021-02-24 08:07 UTC, KarlStraussberger requested changes

2021-02-24 08:07 UTC, KarlStraussberger commented on src/content/content_manager.cc
>  {
This is also an output parameter (see line 441)

2021-02-24 08:07 UTC, KarlStraussberger commented on src/content/content_manager.cc
>      if (obj == nullptr) // object ignored
This is an output parameter

2021-02-24 08:07 UTC, KarlStraussberger commented on src/database/database.cc
>  {
These are output parameters (lines 88 & 90)

2021-02-24 08:07 UTC, KarlStraussberger commented on src/metadata/matroska_handler.cc
>  {
I'm not sure what happens if we copy that stream -> leave it as reference

2021-02-24 08:07 UTC, KarlStraussberger commented on src/metadata/matroska_handler.cc
>  {
I'm not sure what happens if we copy that stream -> leave it as reference

2021-02-24 08:07 UTC, KarlStraussberger commented on src/metadata/metacontent_handler.h
It's `CdsObject `so the paramter should be named `obj`. Maybe it's not done in MetadataHnadler

2021-02-24 08:09 UTC, KarlStraussberger commented
> 
> 
> Updated.

There are a lot more breaking changes. I'd prefer to leave those references as they were.

2021-02-25 08:23 UTC, KarlStraussberger commented on src/metadata/metacontent_handler.h
Please rename the arguments in implentation. Declaration is as it should be.

2021-02-27 21:55 UTC, neheb commented
I removed the reference changes.

2021-02-28 09:07 UTC, KarlStraussberger commented
I also commented on the renamed arguments. The parameters in the headers are fine. The code should be renamed. `item` -> `obj` instead of vice versa.

2021-03-01 07:08 UTC, merged