several clang-tidy and manual cleanups
gerbera/gerbera pull request #1479
Opened 2021-05-28 01:52 UTC by neheb

2021-05-28 05:58 UTC, KarlStraussberger requested changes

2021-05-28 05:58 UTC, KarlStraussberger commented on src/util/process_executor.cc
> +    : process_id(fork())
If you fork here, this may change the behaviour.

2021-05-28 05:58 UTC, KarlStraussberger commented on src/web/session_manager.cc
>      //(new DBRHash<int>(UI_UPDATE_ID_HASH_SIZE, MAX_UI_UPDATE_IDS + 5, INVALID_OBJECT_ID, INVALID_OBJECT_ID_2));
Drop that line, it's old Mediatomb code.

2021-05-29 01:08 UTC, neheb commented on src/config/config_setup.cc
> -        for (auto&& entry : defaultEntries) {
This change fails on debian 10....wtf?

2021-05-29 06:26 UTC, merged