use sizeof for snprintf
gerbera/gerbera pull request #1562
Opened 2021-06-16 20:09 UTC by neheb

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2021-06-16 20:25 UTC, whyman commented
Could we not use fmt?

2021-06-16 20:26 UTC, neheb commented
> Could we not use fmt?

I have no idea honestly. src/main uses C functions everywhere. I don't know the reason.

2021-06-16 21:32 UTC, KarlStraussberger commented
I know: nobody changed it since the first days of mediatomb

2021-06-16 22:40 UTC, neheb commented
Replaced with fmt. The whole codeblock looks like it could be replaced with something simpler.

Anyway, this is good enough for now I think.

2021-06-17 04:24 UTC, KarlStraussberger requested changes

2021-06-17 04:24 UTC, KarlStraussberger commented on src/main.cc
> -            strcat(pidstr, "\n");
You need to add the newline to the output to retain the file format

2021-06-17 07:19 UTC, KarlStraussberger approved these changes

2021-06-17 08:44 UTC, merged