small error handle
gerbera/gerbera pull request #1598
Opened 2021-06-21 07:19 UTC by neheb

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2021-06-21 10:02 UTC, whyman commented
I personally dislike doing work in if conditions.

Can we do the work, assign a `ret` value and then check it?

The compiler will do the right thing, and its much clearer to read.

2021-06-21 10:15 UTC, neheb commented
I mean, the surrounding does similar

2021-06-21 16:16 UTC, whyman commented
Fix that too while you are there? 😄

2021-06-22 20:46 UTC, neheb commented
I think this is what you meant.

2021-06-22 20:57 UTC, KarlStraussberger requested changes

2021-06-22 20:57 UTC, KarlStraussberger commented on src/transcoding/transcode_ext_handler.cc
> +            if (r == -1) {
I'd prefer `!= 0`. Looks more like error handling.

2021-06-22 21:07 UTC, neheb commented on src/transcoding/transcode_ext_handler.cc
> +            if (r == -1) {
OK

2021-06-22 21:15 UTC, KarlStraussberger approved these changes

2021-06-23 04:25 UTC, merged