Code refactoring and performance enhancements in sql_database
gerbera/gerbera pull request #1747
Opened 2021-08-03 19:10 UTC by matthiasstraka

This is essentially the same PR as 1739 but with cleaner commits grouped by function. All previous review remarks are already included in these commits.

2021-08-03 19:26 UTC, matthiasstraka commented
One change I did not yet make but which I would recommend: collapse `table_quote_begin` and `table_quote_end` to `table_quote` which would reduce the SQL generation code significantly (especially now that fmt is used). Currently, begin is the same character as end for both MySQL and SQLite.

2021-08-05 07:12 UTC, KarlStraussberger reviewed
Thanks for helping to improve gerbera. I found one point which could have negative effect on preformance

2021-08-06 21:05 UTC, KarlStraussberger commented on src/database/sql_database.cc
> +        auto res = select(fmt::format("{} {}", sel, quote(objectID)));
> That LIMIT should stay because the result list may be long and we do only need the first

If you readd that `LIMIT` the PR could be merged.

2021-08-10 07:34 UTC, KarlStraussberger requested changes

2021-08-10 07:34 UTC, KarlStraussberger commented on src/database/sql_database.cc
> +        const int objectType =   row->col_int(1);
There is a double space here

2021-08-10 07:34 UTC, KarlStraussberger commented on src/database/sql_database.cc
> +                const int objectType = row->col_int(1);
Add `const int objId = row->col_int(0);` and use it in the following lines;

2021-08-10 07:35 UTC, KarlStraussberger commented
If it wasn't for the double spaces there is no need for a change, but if you have to change just make it even better

2021-08-10 09:42 UTC, matthiasstraka commented
That should be all of the changes (I messed up an attempted squash but that should not be an issue I hope)

2021-08-10 11:36 UTC, KarlStraussberger approved these changes

2021-08-10 11:37 UTC, KarlStraussberger commented
As there have been changes in the master branch in the meantime I cannot automatically rebase. Either you rebase yourself or I squash merge.

2021-08-10 12:14 UTC, matthiasstraka commented
If possible, I'd like you to squash merge my commits together. My fork is currently in a somewhat messed-up state which might cause problems during a rebase.

2021-08-10 18:07 UTC, merged

2021-08-10 18:07 UTC, KarlStraussberger commented
Thank you