various SonarLint cleanups
gerbera/gerbera pull request #2112
Opened 2021-11-02 21:49 UTC by neheb

mostly adding const.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2021-11-02 22:44 UTC, neheb commented
hrm this breaks usage. Setting to draft.

2021-11-03 09:59 UTC, KarlStraussberger requested changes

2021-11-03 09:59 UTC, KarlStraussberger commented on src/content/layout/builtin_layout.cc
> -        case OS_Max:
Code scanning warns about the missing case.

2021-11-03 09:59 UTC, KarlStraussberger commented on src/database/search_handler.cc
> +std::string SearchLexer::getQuotedValue(std::string_view input)
It's a string already, so `string_view` creates a new object instead of passing the existing object.

2021-11-03 09:59 UTC, KarlStraussberger commented on src/file_request_handler.cc
>  {
It's string already.

2021-11-03 09:59 UTC, KarlStraussberger commented on src/database/sqlite3/sqlite_database.cc
> +        cond.wait(lock, [this] { return is_running(); }); // waiting for the task to complete
this is different from the original: Equivalent to

```
while (!stop_waiting()) {
    wait(lock);
}
```

2021-11-03 09:59 UTC, KarlStraussberger commented on src/iohandler/curl_io_handler.cc
> +CurlIOHandler::CurlIOHandler(std::shared_ptr<Config> config, std::string_view url, CURL* curlHandle, std::size_t bufSize, std::size_t initialFillSize)
It's a string already.

2021-11-03 09:59 UTC, KarlStraussberger commented on src/util/tools.cc
> +std::string getProtocol(std::string_view protocolInfo)
It's a string already

2021-11-03 10:04 UTC, neheb commented
I think I'll abandon these for now.

2021-11-03 10:04 UTC, closed without merging