move several methods out of line
gerbera/gerbera pull request #2186
Opened 2021-11-15 10:45 UTC by neheb

Avoids -Wweak-vtables. Small size reduction.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2021-11-15 10:51 UTC, whyman commented
Thanks, can you add the -Wweak-vtables to CMake too?

2021-11-15 11:36 UTC, KarlStraussberger requested changes

2021-11-15 11:36 UTC, KarlStraussberger commented on src/content/scripting/import_script.cc
> +    return S_PLAYLIST;
Must be `S_IMPORT` here

2021-11-15 22:21 UTC, neheb commented
> Thanks, can you add the -Wweak-vtables to CMake too?

Not all are fixed or should be fixed.

2021-11-16 08:03 UTC, whyman commented
> > Thanks, can you add the -Wweak-vtables to CMake too?
> 
> Not all are fixed or should be fixed.

I don't understand why this would be?

2021-11-16 08:08 UTC, neheb commented
Basically, it would require placing out of line definitions for virtual functions. This is somewhat problematic for defaulted destructors. Destructors should always be defaulted in their definitions. Not doing so just increases size for no good reason.

2021-11-16 08:13 UTC, neheb commented
updated slightly.

2021-11-19 06:53 UTC, merged